import { currentActor } from "@/infrastructure/auth";
import { getContainer } from "@/composition/container";
import { scoreBand } from "@/app/(ui)/lib/risk";

/** Export the executive summary as Markdown (PRD F5.4). PDF: use the browser's print-to-PDF. */
export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const actor = await currentActor();
  if (!actor) return new Response("unauthorized", { status: 401 });

  const { id } = await params;
  const { contracts, analyses } = getContainer();
  const contract = await contracts.findById(actor.orgId, id);
  if (!contract) return new Response("not found", { status: 404 });
  const a = await analyses.getByContract(id);
  if (!a) return new Response("no analysis", { status: 404 });

  const md = [
    `# ${contract.title} — Executive Summary`,
    ``,
    `**Overall risk:** ${a.overallRiskScore}/100 (${scoreBand(a.overallRiskScore)})`,
    ``,
    `## Overview`,
    a.overview,
    ``,
    `## Who carries the risk`,
    a.whoCarriesRisk,
    ``,
    `## Key commercial terms`,
    ...a.keyTerms.map((t) => `- **${t.label}:** ${t.value}`),
    ``,
    `## Top issues to negotiate`,
    ...a.topIssues.map((t, i) => `${i + 1}. **${t.title}** — ${t.detail}`),
    ``,
    `---`,
    `_Generated by CasePilot. Decision support, not legal advice._`,
  ].join("\n");

  const safeName = contract.title.replace(/[^\w.\-]+/g, "_");
  return new Response(md, {
    headers: {
      "content-type": "text/markdown; charset=utf-8",
      "content-disposition": `attachment; filename="${safeName}-summary.md"`,
    },
  });
}
